### ISSUE TITLE
todo-server服务启动不了

### ISSUE THREAD

**Issue by linjianzao** [open-dingtalk/weex-dingtalk-todo#1]
![qq 20170811164336](https://user-images.githubusercontent.com/2407785/29206367-41b0e4a8-7eb4-11e7-869c-92e2f8c7267f.png)

打印 helper.js里的os.networkInterfaces().en0 ,显示undefined

![14](https://user-images.githubusercontent.com/2407785/29206545-f5b9e13e-7eb4-11e7-8830-8c211e8bc700.png)

**Comment by icepy** [comment]
这个方法不支持windows，主要是打印ip的，建议在Mac上运行。
